# Generated by Django 3.0.4 on 2020-04-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200401_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='medic_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
