# Generated by Django 3.0.4 on 2020-04-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_medic'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='type',
            field=models.CharField(choices=[('MD', 'Medic'), ('PT', 'Patient')], default='PT', max_length=2),
        ),
    ]
