# Generated by Django 3.0.4 on 2020-04-25 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_extendeduser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='type',
            field=models.CharField(choices=[('NN', 'Not Defined'), ('MD', 'Medic'), ('PT', 'Patient')], default='NN', max_length=3),
        ),
        migrations.CreateModel(
            name='pendingAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.extendedUser')),
            ],
        ),
    ]
