# Generated by Django 3.0.5 on 2020-04-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200426_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
