# Generated by Django 3.0.4 on 2020-04-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200426_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
