# Generated by Django 3.0.5 on 2020-05-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200509_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='firstname',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='lastname',
            field=models.CharField(default='', max_length=500),
        ),
    ]
